### ISSUE TITLE
Missing autoload for Emacs

### ISSUE THREAD

**Issue by berquist** [kjakapat/eva-theme#1]
Right now, it isn't possible to easily clone this repo in an Emacs config and have it automatically available for `load-theme`, since it doesn't modify `custom-theme-load-path` automatically. From https://github.com/belak/base16-emacs/blob/d68512c0856f57a19cd49d1034199836352c15a0/base16-theme.el#L959, some idiomatic code for doing so is
```lisp
;;;###autoload
(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))
```
so the config needs to look something like
```lisp
(use-package base16-eva-theme
  :demand t
  :straight (:host github
             :repo "kjakapat/eva-theme"
             :files ("emacs/build/*.el"))
  :config
  (add-to-list 'custom-theme-load-path
               (concat straight-base-dir
                       "straight/build/base16-eva-theme/"))
  (load-theme 'base16-eva t))
```
if you don't want to just copy the elisp file into your config dir. With the autoload, I could get rid of the `(add-to-list ...` bit.

**Comment by kjakapat** [comment]
I think you should suggest directly to [https://github.com/belak/base16-emacs](https://github.com/belak/base16-emacs). It is better to make the change there because I use it to generate the theme, and it will be useful to a broader community. Once the emacs template fixed, you can notify me to recompile it using _belak/base16-builder-go_. But if you like to modify it from here, you can also do it too, just send me the pull request. 
Anyway, I prefer you to go for the first choice. Thanks for your feedback!

**Comment by berquist** [comment]
I'm not sure what changed, but I removed the `add-to-list` block from the above, and things work now...cheers!
