### ISSUE TITLE
I found that there is something wrong in your st config

### ISSUE THREAD

**Issue by Yakkhini** [kjakapat/eva-theme#2]
This could be the correct color setting:

![2021-05-05-163756_1920x1080_scrot](https://user-images.githubusercontent.com/59007159/117115910-4ea9a980-adc0-11eb-949b-db8b735523e2.png)
![2021-05-05-163736_1920x1080_scrot](https://user-images.githubusercontent.com/59007159/117115918-50736d00-adc0-11eb-9fbb-f27ef4decdbd.png)
(I didn't have a look on dim version so I don't know the file"base16-eva-dim.diff" is correct or not)

By the way, your color scheme is so cool and i love it! Have a good day!

**Comment by kjakapat** [comment]
I don't quite understand your issue, please let me ask you some more questions:

1. What exactly is a problem? (for example, some colors are displayed incorrectly, some files are missing, etc.)
2. Where is the location of the file you have mentioned?
3. How does your suggested solution solve the problem?

Honestly, I know nothing about almost all files in this repository, since I used https://github.com/belak/base16-builder-go to generate them. But please explain some more, maybe I can help you fix it somehow.
